###########################################################
# Dockerfile that builds a Valheim Gameserver
# all thanks to cm2network walentinlamonos@gmail.com. For the steamcmd image and the Mordhau dockerfile.
###########################################################
FROM cm2network/steamcmd:root

LABEL maintainer="kevjan89@gmail.com"

ENV STEAMAPPID 896660
ENV STEAMAPPDIR /home/steam/valheim
ENV VALHEIMSAVE /home/steam/.config/unity3d/IronGate/Valheim
ENV SRVSCRIPT /home/steam/scripts

RUN set -x \
# Install Vallheim server dependencies and clean up
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		libfontconfig1=2.13.1-2 \
		libpangocairo-1.0-0=1.42.4-7~deb10u1 \
		gconf-gsettings-backend=3.2.6-5 \
		libxi6=2:1.7.9-1 \
		libxcursor1=1:1.1.15-2 \
		libxss1=1:1.2.3-1 \
		libxcomposite1=1:0.4.4-2 \
		libasound2=1.1.8-1 \
		libxdamage1=1:1.1.4-3+b3 \
		libxtst6=2:1.2.3-1 \
		libatk1.0-0=2.30.0-2 \
		libxrandr2=2:1.5.1-1 \
	&& apt-get clean autoclean \
	&& apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/* \
# Run Steamcmd and install valheim
# Write Server Config
	&& su steam -c \
		"${STEAMCMDDIR}/steamcmd.sh \
		+login anonymous \
		+force_install_dir ${STEAMAPPDIR} \
		+app_update ${STEAMAPPID} validate \
		+quit" 
		
# Copy Server Script to the Image
RUN mkdir /home/steam/scripts
COPY val_ser.sh /home/steam/scripts

ENV SERVER_Name="replacethis" \
	SERVER_PW="" \
	SERVER_PUBLIC=1 \
	SERVER_PORT=2456 \
	SERVER_WORLD="Dedicated"
			
# Switch to user steam
USER steam

#Workdir 
WORKDIR $STEAMAPPDIR

# Volumes
VOLUME $STEAMAPPDIR
VOLUME $VALHEIMSAVE


# Set Entrypoint
# 1. Update server
# 2. Start the server with your config
ENTRYPOINT ${STEAMCMDDIR}/steamcmd.sh \
			+login anonymous +force_install_dir ${STEAMAPPDIR} +app_update ${STEAMAPPID} +quit \
		&& ${SRVSCRIPT}/val_ser.sh	

# Expose ports
EXPOSE 	2456/udp 2457/udp 2458/udp
